### ISSUE TITLE
Execution failed for task ':react-native-ar-viewer:compileDebugKotlin'

### ISSUE THREAD

**Issue by HimanshiVashist-dev** [riderodd/react-native-ar#101]
I cloned the react-native-ar-viewer repository and was able to run the example project without any issues. However, when I tried to use the package in my own project, I encountered the following error:

![image](https://user-images.githubusercontent.com/128139770/225877913-33f0d5db-b2bf-420b-86bb-db3ebcaa7e57.png)

I followed the instructions in the package's README file, but I'm still getting this error.

The error message specifically states that there is a type mismatch in the ArViewerView.kt file on line 291, where an inferred type is MotionEvent? but MotionEvent was expected. This suggests that there may be an issue with how the MotionEvent type is being used in the code.

I'm not sure how to resolve this issue, so I would appreciate any help or guidance on how to fix this.

Thank you for your assistance!

**Comment by HimanshiVashist-dev** [comment]
I created a React Native project by running the following command: npx react-native init demo. 
Afterwards, I followed the steps outlined in the README.md file.

Step 1: I executed the command npm install react-native-ar-viewer to install the necessary package.

Step 2: I added the following code snippet to the AndroidManifest.xml file:

<meta-data android:name="com.google.ar.core" android:value="required" tools:replace="android:value" />

Step 3: I added the xmlns:tools="http://schemas.android.com/tools" attribute to the <manifest> tag.

However, when I tried to run the application, I encountered an error which is mentioned in the issue.

For your reference, these are the versions of dependencies I am currently using.

![image](https://user-images.githubusercontent.com/128139770/226313056-f840c999-cc67-4ef1-a19e-5e67b03809e2.png)

**Comment by kingdcreations** [comment]
I successfully reproduced the issue, i'm currently working on it

**Comment by kingdcreations** [comment]
Hello ! This should be fixed, please update to 0.1.17 :)

**Comment by HimanshiVashist-dev** [comment]
👋 Hi there!

I incorporated the change you suggested into my project and ran it using the following command:

```npx react-native run-android```

However, when I installed the app on my phone, I encountered the following error. 

![image](https://user-images.githubusercontent.com/128139770/226602592-545109e8-5521-4b7d-b871-7d5a5cb76fc8.png)


##Could you help me rectify this issue?

**Comment by HimanshiVashist-dev** [comment]
### Thanks for your help😊. 

The project is now up and running. The problem I reported earlier has been resolved by following these steps.

Earlier I was adding meta-data tag inside acitivity tag at line 21 like this:

![image](https://user-images.githubusercontent.com/128139770/226614322-7f3e49b6-c556-4f8f-8c05-663486dfd043.png)

The issue is fixed by adding meta-data tag after activity tag at line 27.
