### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Menna123Ali** [riderodd/react-native-ar#107]
I use this code
 <ArViewerView
        style={{flex: 1}}
        model={Platform.OS === 'android' ? 'dice.glb' : 'dice.usdz'}
        lightEstimation
        manageDepth
        allowRotate
        allowScale
        allowTranslate
        disableInstantPlacement
        onStarted={() => console.log('started')}
        onEnded={() => console.log('ended')}
        onModelPlaced={() => console.log('model displayed')}
        onModelRemoved={() => console.log('model not visible anymore')}
        planeOrientation="both"
      />
'dice.glb' and  'dice.usdz' with code in the same folder  .
when i run that example , nothing show in the screen just ask me about camera permission

**Comment by CodingWithNobody** [comment]
This might help https://www.youtube.com/watch?v=46rI2fTr_co

**Comment by kingdcreations** [comment]
Importing local GLB  or USDZ isn't possible
You have to download it from your device
Please look at this example: https://github.com/riderodd/react-native-ar/blob/main/example/src/App.tsx
Hope it helps,
Thaïs
