### ISSUE TITLE
Invite for OSS Viro Community 

### ISSUE THREAD

**Issue by adelarsq** [riderodd/react-native-ar#135]
Hello @riderodd 

How are you?

Some people on discord pointed that you would be interested in [Viro](https://virocommunity.github.io/).

Right now I am looking for OSS contributors to keep It alive. Any help is great!

Are you interested? Ping me on any time :)

**Comment by riderodd** [comment]
Hi @adelarsq !

I'm truly sorry, I have so little time for open source this year that I have to decline. Thanks for having thinking about me for a such great project !

**Comment by adelarsq** [comment]
@riderodd Thanks! No problem. I am in the same spot. I am also most working with commercial stuff. Feel free to reach me out on any time!

**Comment by quangArchiviet** [comment]
@riderodd Hi, how about now? We really hope you can participate in the development of Viro (NativeVision now)

**Comment by riderodd** [comment]
I'm sorry I still can't, I'm too busy for now. But thank you for the invite!
